export const LOGIN = "LOGIN";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const DETAILS = "DETAILS";
export const DETAILS_START = "DETAILS_START";
export const DETAILS_SUCCESS = "DETAILS_SUCCESS";
export const DETAILS_FAILURE = "DETAILS_FALIURE";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_START = "CHANGE_PASSWORD_START";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

export const FETCH_ORDER = "FETCH_ORDER";
export const FETCH_ORDER_START = "FETCH_ORDER_START";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAILURE = "FETCH_ORDER_FAILURE";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILURE = "FETCH_ORDERS_FAILURE";

export const CHECK_TOKEN_VALIDITY = "CHECK_TOKEN_VALIDITY";
export const TOKEN_VALIDITY_START = "TOKEN_VALIDITY_START";
export const TOKEN_VALIDITY_SUCCESS = "TOKEN_VALIDITY_SUCCESS";
export const TOKEN_VALIDITY_FAILURE = "TOKEN_VALIDITY_FAILURE";

export const SET_PASSWORD = "SET_PASSWORD";
export const SET_PASSWORD_START = "SET_PASSWORD_START";
export const SET_PASSWORD_SUCCESS = "SET_PASSWORD_SUCCESS";
export const SET_PASSWORD_FAILURE = "SET_PASSWORD_FAILURE";

export const TRANSITION = "TRANSITION";
export const TRANSITION_START = "TRANSITION_START";
export const TRANSITION_SUCCESS = "TRANSITION_SUCCESS";
export const TRANSITION_FAILURE = "TRANSITION_FAILURE";
